### ISSUE TITLE
get请求很慢

### ISSUE THREAD

**Issue by bdss58** [coderLMN/secretDoor#1]
![image](https://cloud.githubusercontent.com/assets/5461407/11389260/8906192c-9379-11e5-8fa8-ec13593871b6.png)
是不是mongo查询慢了？

**Comment by coderLMN** [comment]
可能有几个原因：
1. 我用的是免费的 server 和 mongodb，性能比较渣，但是现在数据量还小，应该不至于；
2. 原先的前端代码里对 DOM 操作太频繁，估计这个是主要原因，刚才我已经改掉了；
3. 也有可能是你那边的网络访问北美服务器（Heroku 的服务器在美国）的速度慢。

**Comment by bdss58** [comment]
恩，应该不是mongo的问题。主要是访问北美服务器慢。DOM操作改的赞~~LOL

**Comment by coderLMN** [comment]
刚看到你的图，看来和DOM操作也没关系，哈哈
